FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run storybook-build

FROM nginx:stable-alpine AS runtime

COPY --from=build /app/storybook-static /usr/share/nginx/html

EXPOSE 80
